import tkinter
from tkinter import *
root=Tk()
root.geometry('290x235')
root.maxsize(304,235)
root.minsize(304,235)
root.title('Calculator')
root.wm_iconbitmap('2.ico')
fm=Frame(width=304,height=235 ,bg='#C1CDCD')
fm.propagate(0)
fm.pack()
l1=Entry(fm, fg='black', bg='White', width=48)
l1.place(x=8,y=15)
btn1=Button(fm,height=2,width=6,text='1',bg='#C1CDCD',fg='black',command=lambda :click(1))
btn1.place(x=10,y=50)
btn2=Button(fm,height=2,width=6,text='2',bg='#C1CDCD',fg='black',command=lambda :click(2))
btn2.place(x=62,y=50)
btn3=Button(fm,height=2,width=6,text='3',bg='#C1CDCD',fg='black',command=lambda :click(3))
btn3.place(x=114,y=50)
btn4=Button(fm,height=2,width=6,text='4',bg='#C1CDCD',fg='black',command=lambda :click(4))
btn4.place(x=10,y=91)
btn5=Button(fm,height=2,width=6,text='5',bg='#C1CDCD',fg='black',command=lambda :click(5))
btn5.place(x=62,y=91)
btn6=Button(fm,height=2,width=6,text='6',bg='#C1CDCD',fg='black',command=lambda :click(6))
btn6.place(x=114,y=91)
btn7=Button(fm,height=2,width=6,text='7',bg='#C1CDCD',fg='black',command=lambda :click(7))
btn7.place(x=10,y=132)
btn8=Button(fm,height=2,width=6,text='8',bg='#C1CDCD',fg='black',command=lambda :click(8))
btn8.place(x=62,y=132)
btn9=Button(fm,height=2,width=6,text='9',bg='#C1CDCD',fg='black',command=lambda :click(9))
btn9.place(x=114,y=132)
btnp=Button(fm,height=2,width=8,text='+',bg='#8E8E8E',fg='black',command=lambda :click('+'))
btnp.place(x=166,y=50)
btns=Button(fm,height=2,width=8,text='-',bg='#8E8E8E',fg='black',command=lambda :click('-'))
btns.place(x=232,y=50)
btnm=Button(fm,height=2,width=8,text='*',bg='#8E8E8E',fg='black',command=lambda :click('*'))
btnm.place(x=166,y=91)
btnd=Button(fm,height=2,width=8,text='/',bg='#8E8E8E',fg='black',command=lambda :click('/'))
btnd.place(x=232,y=91)
btnc=Button(fm,height=2,width=8,text='%',bg='#8E8E8E',fg='black',command=lambda :click('%'))
btnc.place(x=166,y=132)
btnmd=Button(fm,height=2,width=8,text='AC',bg='#FFA54F',fg='black',command=lambda:clear())
btnmd.place(x=232,y=132)
btn0=Button(fm,height=2,width=8,text='0',bg='#C1CDCD',fg='black',command=lambda :click(0))
btn0.place(x=10,y=173)
btndt=Button(fm,height=2,width=5,text='.',bg='#8E8E8E',fg='black',command=lambda :click('.'))
btndt.place(x=76,y=173)
btnlp=Button(fm,height=2,width=5,text='(',bg='#8E8E8E',fg='black',command=lambda :click('('))
btnlp.place(x=121,y=173)
btnrp=Button(fm,height=2,width=6,text=')',bg='#8E8E8E',fg='black',command=lambda :click(')'))
btnrp.place(x=166,y=173)
btnok=Button(fm,height=2,width=10,text='=',bg='#FFA54F',fg='black',command=lambda :equal())
btnok.place(x=218,y=173)
def click(n):
    l1.insert(tkinter.END,n)
def clear():
    l1.delete(0,tkinter.END)
def equal():
    result=str(eval(l1.get()))
    l1.delete(0,tkinter.END)
    l1.insert(tkinter.END,result)
root.mainloop()